language: ruby
script: "bundle exec rake test"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - jeremy.olliver@gmail.com
